Updates to merge in changes from install job work
TonicAI/timothy_helm_charts pull request #1
Opened 2023-02-10 18:09 UTC by daniel-tonic

2023-02-10 23:30 UTC, anr-tonic requested changes

2023-02-10 23:30 UTC, anr-tonic commented on values.yaml
> +  installName: "tonicai/timothy_install"
Instead of renaming `name` can we stick these properties on the `timBot` key (and maybe a better name for it as well lol)

2023-02-10 23:30 UTC, anr-tonic commented on templates/_helpers.tpl
> +{{- define "timothy.webImage" -}}
Good w/ this rename. Don't wanna cause confusion based on my comment about values.yaml structure.

2023-02-28 21:01 UTC, anr-tonic commented on templates/deployment.yaml
>              - name: INSTALL_IMAGE
Should we adjust this to `INSTALL_JOB_IMAGE` to match the role?

2023-03-01 21:04 UTC, anr-tonic requested changes
We need to update the first part of the readme where `configuration.database` is mentioned as well as `annotations` at the bottom to `web.annotations`

2023-03-01 21:04 UTC, anr-tonic commented on values.yaml
> +    enabled: true
We should keep the default to false and set it to true by default in our installers.

2023-03-01 21:06 UTC, daniel-tonic commented on values.yaml
> +    enabled: true
Good catch.  It was a copy/paste from my local test file.

2023-03-01 21:24 UTC, anr-tonic approved these changes

2023-03-02 18:56 UTC, merged